const express = require('express');
const authController = require('../controllers/admin/authController');
const dashboardController = require('../controllers/admin/dashboardController');
const contentController = require('../controllers/admin/contentController');
const pageController = require('../controllers/admin/pageController');
const settingsController = require('../controllers/admin/settingsController');
const mediaController = require('../controllers/admin/mediaController');
const moduleController = require('../controllers/admin/moduleController');
const seoController = require('../controllers/admin/seoController');
const submissionController = require('../controllers/admin/submissionController');
const { requireAuth, requireGuest } = require('../middleware/auth');
const upload = require('../config/upload');

const router = express.Router();

router.get('/login', requireGuest, authController.showLogin);
router.post('/login', requireGuest, authController.login);
router.post('/logout', requireAuth, authController.logout);

router.get('/', requireAuth, dashboardController.index);
router.get('/content', requireAuth, contentController.index);
router.get('/pages', requireAuth, pageController.index);
router.get('/pages/:id/edit', requireAuth, pageController.edit);
router.post('/pages/:id', requireAuth, pageController.update);
router.post('/sections/:id', requireAuth, pageController.updateSection);
router.post('/section-items', requireAuth, pageController.createSectionItem);
router.post('/section-items/:id', requireAuth, pageController.updateSectionItem);
router.post('/section-items/:id/delete', requireAuth, pageController.deleteSectionItem);
router.post('/section-media', requireAuth, pageController.createSectionMedia);
router.post('/section-media/:id/delete', requireAuth, pageController.deleteSectionMedia);
router.get('/contact-block', requireAuth, settingsController.contactBlock);
router.post('/contact-block', requireAuth, settingsController.updateContactBlock);
router.get('/footer', requireAuth, settingsController.footer);
router.post('/footer', requireAuth, settingsController.updateFooter);
router.get('/seo', requireAuth, seoController.index);
router.get('/seo/:id/edit', requireAuth, seoController.edit);
router.post('/seo/:id', requireAuth, seoController.update);
router.get('/media', requireAuth, settingsController.media);
router.post('/media', requireAuth, upload.array('images', 12), mediaController.upload);
router.post('/media/:id/delete', requireAuth, mediaController.delete);
router.get('/modules/:module', requireAuth, moduleController.index);
router.get('/modules/:module/create', requireAuth, moduleController.createForm);
router.post('/modules/:module', requireAuth, moduleController.create);
router.get('/modules/:module/:id/edit', requireAuth, moduleController.editForm);
router.post('/modules/:module/:id', requireAuth, moduleController.update);
router.post('/modules/:module/:id/delete', requireAuth, moduleController.delete);
router.get('/submissions/:type', requireAuth, submissionController.index);
router.post('/submissions/:type/:id/delete', requireAuth, submissionController.delete);

module.exports = router;
